{% set version = "8.39" %}

package:
  name: pcre
  version: {{ version }}

source:
  fn: pcre-{{ version }}.tar.gz
  url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-{{ version }}.tar.gz
  sha256: ccdf7e788769838f8285b3ee672ed573358202305ee361cfec7a4a4fb005bbc7

build:
  number: 0
  features:
    - vc9          # [win and py27]
    - vc10         # [win and py34]
    - vc14         # [win and py>=35]
    
requirements:
  build:
    - python       # [win]
    - cmake        # [win]
    - pkg-config   # [unix]
    - libtool      # [unix]
    - vc   9       # [win and py27]
    - vc  10       # [win and py34]
    - vc  14       # [win and py>=35]
    
  run:
    - vc   9       # [win and py27]
    - vc  10       # [win and py34]
    - vc  14       # [win and py>=35]

test:
  commands:
    # CLI tests.
    - pcre-config --version                             # [unix]
    - pcregrep --help
    - pcretest --help

    # Verify headers.
    - test -f "${PREFIX}/include/pcre.h"                # [unix]
    - test -f "${PREFIX}/include/pcre_scanner.h"        # [unix]
    - test -f "${PREFIX}/include/pcre_stringpiece.h"    # [unix]
    - test -f "${PREFIX}/include/pcrecpp.h"             # [unix]
    - test -f "${PREFIX}/include/pcrecpparg.h"          # [unix]
    - test -f "${PREFIX}/include/pcreposix.h"           # [unix]
    - if not exist %LIBRARY_INC%\pcre.h exit 1          # [win]
    - if not exist %LIBRARY_INC%\pcre_scanner.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\pcre_stringpiece.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\pcrecpp.h exit 1       # [win]
    - if not exist %LIBRARY_INC%\pcrecpparg.h exit 1    # [win]
    - if not exist %LIBRARY_INC%\pcreposix.h exit 1     # [win]

    # Verify libraries.
    - test -f "${PREFIX}/lib/libpcre.a"                 # [unix]
    - test -f "${PREFIX}/lib/libpcre.so"                # [linux]
    - test -f "${PREFIX}/lib/libpcre.dylib"             # [osx]
    - test -f "${PREFIX}/lib/libpcrecpp.a"              # [unix]
    - test -f "${PREFIX}/lib/libpcrecpp.so"             # [linux]
    - test -f "${PREFIX}/lib/libpcrecpp.dylib"          # [osx]
    - test -f "${PREFIX}/lib/libpcreposix.a"            # [unix]
    - test -f "${PREFIX}/lib/libpcreposix.so"           # [linux]
    - test -f "${PREFIX}/lib/libpcreposix.dylib"        # [osx]
    - if not exist %LIBRARY_LIB%\pcre.lib exit 1        # [win]
    - if not exist %LIBRARY_BIN%\pcre.dll exit 1        # [win]
    - if not exist %LIBRARY_LIB%\pcreposix.lib exit 1   # [win]
    - if not exist %LIBRARY_BIN%\pcreposix.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\pcrecpp.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\pcrecpp.dll exit 1     # [win]

about:
  home: http://www.pcre.org/
  license: BSD 3-Clause
  summary: Regular expression pattern matching using the same syntax and semantics as Perl 5.

extra:
  recipe-maintainers:
    - jakirkham
    - scopatz
    - sebastian-luna-valero
